# -*- coding: utf-8 -*-
"""Copy of Postgres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X54MACCZEMih3zFOSVviPHOtCMXw5Z4u
"""

pip install psycopg2-binary pandas sqlalchemy -q

model = "gemini-2.5-flash"
DATABASE_URL = (
    "postgresql://neondb_owner:npg_bF0jXorLh8NM@ep-patient-feather-a1xgoy13-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
)

# postgres,mysql,tsql,bigquery,snowflake
database = 'postgres'

from google import genai
from google.genai import types

# client = genai.Client(api_key="AIzaSyDBnJRVwolMpxQEEsU_syZKGgWjaWEd5yw")
client = genai.Client(api_key="AIzaSyD9qRPGKMm9orOf54ObME4UakrG_dpA0oc")

def gemini_call(sql_prompt,user_query=None):
  if user_query:
      print(f"Calling Gemini with {user_query}")
      response = client.models.generate_content(
      model=model,
      config=types.GenerateContentConfig(
          system_instruction=sql_prompt),
      contents=user_query
  )
      print("call done")
      gemini_response=response.text
  else:
      response = client.models.generate_content(
      model=model,
      config=types.GenerateContentConfig(
          system_instruction=sql_prompt),
      contents="Answer me"
  )
      gemini_response=response.text


  if gemini_response.startswith("```"):
      gemini_response = gemini_response.replace("```sql", "")
      gemini_response = gemini_response.replace("```python", "")
      gemini_response = gemini_response.replace("```", "")
  return gemini_response

# print(gemini_call(sql_prompt,'most sold products in 2017'))

import psycopg2

def get_database_schema(DATABASE_URL, table_names=None):
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    # -------------------- GET TABLE LIST --------------------
    if table_names is None:
        cur.execute("""
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_type = 'BASE TABLE';
        """)
        table_names = [t[0] for t in cur.fetchall()]

    final_output = []

    for table_name in table_names:
        output = []

        # -------------------- COLUMNS --------------------
        cur.execute("""
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
            ORDER BY ordinal_position;
        """, (table_name,))

        columns = cur.fetchall()
        if not columns:
            continue

        output.append(f"\n📋 Table: {table_name}")
        output.append("-" * 60)
        output.append(f"{'Column':20} {'Type':15} {'Nullable':10} {'Default'}")

        for col in columns:
            output.append(f"{col[0]:20} {col[1]:15} {col[2]:10} {col[3]}")

        # -------------------- PRIMARY KEY --------------------
        cur.execute("""
            SELECT kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_schema = 'public'
              AND tc.table_name = %s
              AND tc.constraint_type = 'PRIMARY KEY';
        """, (table_name,))

        pk = [r[0] for r in cur.fetchall()]
        if pk:
            output.append("\n🔑 Primary Key:")
            output.append("   " + ", ".join(pk))

        # -------------------- FOREIGN KEYS --------------------
        cur.execute("""
            SELECT
                kcu.column_name,
                ccu.table_name,
                ccu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
            WHERE tc.table_schema = 'public'
              AND tc.table_name = %s
              AND tc.constraint_type = 'FOREIGN KEY';
        """, (table_name,))

        fk_rows = cur.fetchall()
        if fk_rows:
            output.append("\n🔗 Foreign Keys:")
            for col, ft, fc in fk_rows:
                output.append(f"   {col} → {ft}.{fc}")

        # -------------------- REFERENCED BY --------------------
        cur.execute("""
            SELECT tc.table_name, kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema = 'public'
              AND ccu.table_name = %s;
        """, (table_name,))

        refs = cur.fetchall()
        if refs:
            output.append("\n🔁 Referenced By:")
            for t, c in refs:
                output.append(f"   {t}.{c} → {table_name}")

        final_output.append("\n".join(output))

    cur.close()
    conn.close()

    return "\n\n".join(final_output)

print(get_database_schema(DATABASE_URL))

import json
import psycopg2

def get_unique_context_columns(schema_string, DATABASE_URL, limit=15):
    """
    1. Uses Gemini to find low-cardinality columns
    2. Fetches unique values for those columns from DB
    3. Returns formatted output
    """

    # ---------- STEP 1: Ask Gemini ----------
    prompt = f"""
    You have to find the columns which have minimum unique values
    for setting them as context in my SQL AI agent.

    Schema:
    {schema_string}

    Return strictly JSON only in this format:
    [
        {{"table_name": "column_name"}}
    ]
    """

    unique_columns = gemini_call(prompt)

    # Clean Gemini output
    # if unique_columns.startswith("```"):
    unique_columns = unique_columns.replace("```", "")
    unique_columns = unique_columns.replace("json", "")
    print(unique_columns)
    table_column_list = json.loads(unique_columns)

    # ---------- STEP 2: Fetch values from DB ----------
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    output = []

    for item in table_column_list:
        for table, column in item.items():

            query = f"""
                SELECT DISTINCT {column}
                FROM {table}
                WHERE {column} IS NOT NULL
                ORDER BY {column}
                LIMIT %s;
            """

            try:
                cur.execute(query, (limit,))
                values = [str(row[0]) for row in cur.fetchall()]

                output.append(
                    f"\n📋 {table}.{column} (top {limit} unique values):"
                )
                output.append(", ".join(values) if values else "No values found")

            except Exception as e:
                output.append(
                    f"\n❌ Error fetching {table}.{column}: {str(e)}"
                )
                conn.rollback()

    cur.close()
    conn.close()

    return "\n".join(output)

print(get_unique_context_columns(get_database_schema(DATABASE_URL), DATABASE_URL))

# from datetime import datetime
# schema_string=get_table_details(get_tables())
# unique_data_columns=get_unique_value_columns()
# unique_value=get_unique_column_values(unique_data_columns)

def create_query_prompt(query,schema_string,unique_value):
  date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
  query_gen_prompt=f"""You are an SQL query generator.

DATABASE SCHEMA:
{schema_string}

ADDITIONAL INFORMATION:
{unique_value}

DATE:
{date}

STRICT RULES (MUST FOLLOW):
- Output ONLY a valid SQL query
- DO NOT explain anything
- DO NOT add comments
- DO NOT use markdown
- DO NOT include backticks
- DO NOT include headings or extra text
- Output must start with SELECT
- Use {database} syntax only
- Use only the given tables and columns
- Do NOT invent columns
- Use column names exactly as provided
- Strictly abide by column data types
- If a column represents date or time and its type is TEXT, CAST it to timestamp before any date operation
- Do NOT use STRFTIME, YEAR, DATE_FORMAT, or non-{database} functions
- Prefer date range filtering over extracting year/month when possible
- If a column name exists in more than one joined table, always prefix it with the table alias
- Generate a SINGLE SQL query only

FAILURE CONDITION:
If the output contains anything other than raw SQL, it is incorrect.

OUTPUT:
<SQL Query>

"""
  return query_gen_prompt
# print(create_query_prompt("Hii"))

import pandas as pd
import sys
import psycopg2
import os



def data_retriver(sql_query , DATABASE_URL):
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    cur.execute(sql_query)
    data = cur.fetchall()

    df = pd.DataFrame(
        data,
        columns=[desc[0] for desc in cur.description]
    )

    if len(data) == 0:
        print("no data found")

    elif len(data) == 1:
        print(data)
        #return data -- vitthal
        return data
        cur.close()
        conn.close()
        sys.exit(0)

    else:
        if os.path.exists('tables.csv'):
           os.remove('tables.csv')
        df.to_csv('tables.csv', index=False)

    cur.close()
    conn.close()
    return data

import json
import pandas as pd

def create_script_prompt(sql_query,user_query):
    df = pd.read_csv('/content/tables.csv', header=None)

    first_five_row = df.head(5).values.tolist()
    last_five_row = df.tail(5).values.tolist()

    first_str = json.dumps(first_five_row)
    last_str = json.dumps(last_five_row)

    sample = first_str + last_str

    script_gen_prompt = f"""Generate a single Python script only (no explanation, no markdown).

Requirements:
1. The script must contain exactly ONE function.
2. The function must be called within the same script.
3. The script must read a CSV file located at: /content/tables.csv
4. The CSV has NO header.
6. Detect:
   - One categorical column (string/object type) → use for X-axis
   - One numeric column → use for Y-axis
7. Use pandas for data handling.
8. Use seaborn or matplotlib for visualization.
10. Ensure numeric columns are converted properly before plotting.
11. Add:
    - Chart title
    - X-axis label
    - Y-axis label
    - Rotated x-axis labels
12. The script must run correctly using exec().
13. Do NOT include explanations, comments, or markdown.
14. Output must be valid executable Python code only.

Sample data:
{sample}

Use properly readable and intuitive labels.
This is my SQL query use to retrive data: {sql_query}
This is my user query: {user_query}
CSV contains {len(df.index)} rows.
You may generate multiple graphs. Each graph must be a separate image.
When reading CSV files, respect header rows and use try–except with a safe fallback so that if one parsing or date-handling approach fails, an alternative method is attempted instead of stopping execution.

Store the graphs in /content/Graphs
"""
    return script_gen_prompt
    # print(script_gen_prompt)
# create_script_prompt(sql_query)

# script_prompt=create_script_prompt(sql_query)
# # script=gemini_call(script_prompt)
# print(script)
# # print(gemini_call(script_prompt))

from sqlglot import exp

# Expressions NOT supported by SQL dialect

POSTGRES_DENYLIST = (
    exp.Qualify,
    exp.Pivot,
    exp.Struct,
)

MYSQL_DENYLIST = (
    exp.Qualify,
    exp.Pivot,
    exp.Struct,
)

TSQL_DENYLIST = (
    exp.Qualify,
    exp.Struct,
)

BIGQUERY_DENYLIST = (
    exp.Pivot,
)

SNOWFLAKE_DENYLIST = (
    exp.Struct,
)

from sqlglot import exp

def has_distinct_on(parsed) -> bool:
    d = parsed.find(exp.Distinct)
    return bool(d and d.args.get("on"))

def has_pg_cast(sql: str) -> bool:
    return "::" in sql

def has_ilike(parsed) -> bool:
    return parsed.find(exp.ILike) is not None

def has_top(parsed) -> bool:
    return parsed.find(exp.Top) is not None

import sqlglot
from sqlglot.errors import ParseError

# Expressions NOT supported by PostgreSQL

def postgres_select_guardrail(sql_query: str) -> bool:
    try:
        parsed = sqlglot.parse_one(sql_query, dialect="postgres")
    except ParseError:
        return False

    if not isinstance(parsed, (exp.Select, exp.With)):
        return False

    if isinstance(parsed, exp.With) and not isinstance(parsed.this, exp.Select):
        return False

    for forbidden in POSTGRES_DENYLIST:
        if parsed.find(forbidden):
            return False

    return True

def mysql_select_guardrail(sql_query: str) -> bool:
    try:
        parsed = sqlglot.parse_one(sql_query, dialect="mysql")
    except ParseError:
        return False

    if not isinstance(parsed, (exp.Select, exp.With)):
        return False

    if isinstance(parsed, exp.With) and not isinstance(parsed.this, exp.Select):
        return False

    for forbidden in MYSQL_DENYLIST:
        if parsed.find(forbidden):
            return False

    if has_distinct_on(parsed):
        return False

    if has_pg_cast(sql_query):
        return False

    return True

def tsql_select_guardrail(sql_query: str) -> bool:
    try:
        parsed = sqlglot.parse_one(sql_query, dialect="tsql")
    except ParseError:
        return False

    if not isinstance(parsed, (exp.Select, exp.With)):
        return False

    if isinstance(parsed, exp.With) and not isinstance(parsed.this, exp.Select):
        return False

    for forbidden in TSQL_DENYLIST:
        if parsed.find(forbidden):
            return False

    if has_distinct_on(parsed):
        return False

    if has_pg_cast(sql_query):
        return False

    return True

def bigquery_select_guardrail(sql_query: str) -> bool:
    try:
        parsed = sqlglot.parse_one(sql_query, dialect="bigquery")
    except ParseError:
        return False

    if not isinstance(parsed, (exp.Select, exp.With)):
        return False

    if isinstance(parsed, exp.With) and not isinstance(parsed.this, exp.Select):
        return False

    for forbidden in BIGQUERY_DENYLIST:
        if parsed.find(forbidden):
            return False

    if has_distinct_on(parsed):
        return False

    if has_pg_cast(sql_query):
        return False

    return True

def snowflake_select_guardrail(sql_query: str) -> bool:
    try:
        parsed = sqlglot.parse_one(sql_query, dialect="snowflake")
    except ParseError:
        return False

    if not isinstance(parsed, (exp.Select, exp.With)):
        return False

    if isinstance(parsed, exp.With) and not isinstance(parsed.this, exp.Select):
        return False

    for forbidden in SNOWFLAKE_DENYLIST:
        if parsed.find(forbidden):
            return False

    if has_distinct_on(parsed):
        return False

    if has_pg_cast(sql_query):
        return False

    return True

GUARDRAILS = {
    "postgres": postgres_select_guardrail,
    "mysql": mysql_select_guardrail,
    "tsql": tsql_select_guardrail,
    "bigquery": bigquery_select_guardrail,
    "snowflake": snowflake_select_guardrail,
}

def validate_sql(sql: str, dialect: str) -> bool:
    guardrail = GUARDRAILS.get(dialect)
    if not guardrail:
        raise ValueError(f"Unsupported dialect: {dialect}")
    return guardrail(sql)

print(validate_sql('SELECT DISTINCT ON (department_id) id,name,department_id,created_at FROM employees ORDER BY department_id, created_at DESC;',database))

def setup():
  schema_string= get_database_schema(DATABASE_URL)
    # print(schema_string)
  unique_value = get_unique_context_columns(schema_string ,DATABASE_URL)
  # print(unique_value)
  return schema_string,unique_value
    # print(unique_value)

from datetime import datetime
def main():
  schema_string,unique_value=setup()
  while(True):
    user_query = input("Let's do some magic! Ask the SQL genie..")
    sql_prompt = create_query_prompt(user_query,schema_string,unique_value)

    sql_query = gemini_call(sql_prompt,user_query)
    print(sql_query)
    flag = validate_sql(sql_query,database)

    if not flag:
          print('Data modification query')
    else:
      data_retriver(sql_query,DATABASE_URL)
      script_prompt=create_script_prompt(sql_query,user_query)
      script=gemini_call(script_prompt)
        # print(script)
      exec(script,globals())

main()

